
const ACTION_TYPES = {
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  SWITCH_FILTER: 'SWITCH_FILTER',
  ADD_TODO: 'ADD_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  TOGGLE_ALL: 'TOGGLE_ALL',
};

export default ACTION_TYPES;

